apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: vault
  name: vault
spec:
  type: LoadBalancer
  ports:
    - name: "8400"
      port: 8400
      targetPort: 8400
  selector:
    io.kompose.service: vault
status:
  loadBalancer: {}

